Repository Medusa-Team/linux-medusa, pull requests merged in 2020-07, with the labels that each got.

#15 Fix sleeping bug in auth server registration
  security/medusa/l3/registry.c
  security/medusa/l4-constable/Makefile
  security/medusa/l4-constable/chardev.c
  security/medusa/l4-constable/med_cache.c
  security/medusa/l4-constable/med_cache.h
Labels: bug

#18 Fix memory leaks on ipc, task and inode security struct allocation.
  security/medusa/l1/medusa.c
Labels: bug

#19 Fix in all IPC acctypes trigger testing.
  security/medusa/l2/acctype_ipc_associate.c
  security/medusa/l2/acctype_ipc_ctl.c
  security/medusa/l2/acctype_ipc_msgrcv.c
  security/medusa/l2/acctype_ipc_msgsnd.c
  security/medusa/l2/acctype_ipc_permission.c
  security/medusa/l2/acctype_ipc_semop.c
  security/medusa/l2/acctype_ipc_shmat.c
Labels: bug

#20 Remove L0 layer code from Medusa.
  security/medusa/Makefile
  security/medusa/l0/Makefile
  security/medusa/l0/init_medusa.c
  security/medusa/l0/init_medusa.h
  security/medusa/l1/medusa.c
Labels: unused

#21 Coding style ipc acctypes
  security/medusa/l2/acctype_ipc_associate.c
  security/medusa/l2/acctype_ipc_ctl.c
  security/medusa/l2/acctype_ipc_msgrcv.c
  security/medusa/l2/acctype_ipc_msgsnd.c
  security/medusa/l2/acctype_ipc_permission.c
  security/medusa/l2/acctype_ipc_semop.c
  security/medusa/l2/acctype_ipc_shmat.c
Labels: enhancement
